"""New Migration

Revision ID: 04633c4d5560
Revises: 1e6984fe61aa
Create Date: 2024-06-15 06:55:38.396479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04633c4d5560'
down_revision = '1e6984fe61aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
