"""New Migration

Revision ID: 0887db33dfbe
Revises: 5d2b5c0fb2f7
Create Date: 2023-12-13 07:22:11.698638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0887db33dfbe'
down_revision = '5d2b5c0fb2f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tel_number', sa.String(), nullable=True))
    op.add_column('user', sa.Column('whatsapp_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'whatsapp_number')
    op.drop_column('user', 'tel_number')
    # ### end Alembic commands ###
