"""New Migration

Revision ID: 0ea968a2148d
Revises: c5c11842a3a2
Create Date: 2024-01-05 04:07:19.728476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea968a2148d'
down_revision = 'c5c11842a3a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('free', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('house', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('job', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('sharedroom', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sharedroom', 'views')
    op.drop_column('job', 'views')
    op.drop_column('house', 'views')
    op.drop_column('free', 'views')
    op.drop_column('event', 'views')
    # ### end Alembic commands ###
