"""New Migration

Revision ID: 11b14f42f75f
Revises: 1edfb8ce4b74
Create Date: 2023-08-29 19:03:28.475341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b14f42f75f'
down_revision = '1edfb8ce4b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
