"""New Migration

Revision ID: 1242ddc162b5
Revises: 58626a3bb050
Create Date: 2024-06-11 07:00:18.272885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1242ddc162b5'
down_revision = '58626a3bb050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
