"""New Migration

Revision ID: 130cb3ac2bfb
Revises: 2c1e6afcef75
Create Date: 2024-03-12 01:18:36.709616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130cb3ac2bfb'
down_revision = '2c1e6afcef75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('general', sa.Column('longitude', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('general', 'longitude')
    op.drop_column('general', 'latitude')
    # ### end Alembic commands ###
