"""New Migration

Revision ID: 1314cd3c7150
Revises: 1c1574156ee8
Create Date: 2024-07-02 05:38:13.836030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1314cd3c7150'
down_revision = '1c1574156ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
