"""New Migration

Revision ID: 147f0aa257d6
Revises: 8f75593e2b6e
Create Date: 2023-08-25 05:10:40.114707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147f0aa257d6'
down_revision = '8f75593e2b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
