"""New Migration

Revision ID: 1c1574156ee8
Revises: 4aff2199bee4
Create Date: 2024-07-02 05:37:25.345312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1574156ee8'
down_revision = '4aff2199bee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otpblocks', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('otpblocks', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('otpblocks', sa.Column('encrypted_password', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otpblocks', 'encrypted_password')
    op.drop_column('otpblocks', 'last_name')
    op.drop_column('otpblocks', 'first_name')
    # ### end Alembic commands ###
