"""New Migration

Revision ID: 1e6984fe61aa
Revises: 7a418b5592eb
Create Date: 2024-06-15 04:49:08.133170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6984fe61aa'
down_revision = '7a418b5592eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businessrequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businessrequest_id'), 'businessrequest', ['id'], unique=False)
    op.create_index(op.f('ix_businessrequest_place_id'), 'businessrequest', ['place_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_businessrequest_place_id'), table_name='businessrequest')
    op.drop_index(op.f('ix_businessrequest_id'), table_name='businessrequest')
    op.drop_table('businessrequest')
    # ### end Alembic commands ###
