"""New Migration

Revision ID: 28e502f86041
Revises: 91895ee943bd
Create Date: 2024-02-21 15:10:45.488807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e502f86041'
down_revision = '91895ee943bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('owner_name', sa.String(), nullable=True))
    op.add_column('comment', sa.Column('owner_last_name', sa.String(), nullable=True))
    op.add_column('comment', sa.Column('created_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'created_on')
    op.drop_column('comment', 'owner_last_name')
    op.drop_column('comment', 'owner_name')
    # ### end Alembic commands ###
