"""New Migration

Revision ID: 2a43291639bc
Revises: 3d483f90a031
Create Date: 2024-02-20 02:34:18.094741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a43291639bc'
down_revision = '3d483f90a031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
