"""New Migration

Revision ID: 2b5cf13f8bb0
Revises: 6b74c60fb403
Create Date: 2023-08-29 00:12:22.139612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5cf13f8bb0'
down_revision = '6b74c60fb403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
