"""New Migration

Revision ID: 2bde4b0b48a3
Revises: b2bca5819eb9
Create Date: 2024-02-15 01:16:29.528716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bde4b0b48a3'
down_revision = 'b2bca5819eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
