"""New Migration

Revision ID: 2beb7407deeb
Revises: 130cb3ac2bfb
Create Date: 2024-05-16 06:52:47.330073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2beb7407deeb'
down_revision = '130cb3ac2bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_interest')
    op.add_column('event', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('event', sa.Column('longitude', sa.String(), nullable=True))
    op.add_column('house', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('house', sa.Column('longitude', sa.String(), nullable=True))
    op.add_column('job', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('job', sa.Column('longitude', sa.String(), nullable=True))
    op.add_column('sharedroom', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('sharedroom', sa.Column('longitude', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sharedroom', 'longitude')
    op.drop_column('sharedroom', 'latitude')
    op.drop_column('job', 'longitude')
    op.drop_column('job', 'latitude')
    op.drop_column('house', 'longitude')
    op.drop_column('house', 'latitude')
    op.drop_column('event', 'longitude')
    op.drop_column('event', 'latitude')
    op.create_table('post_interest',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interest_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interest.id'], name='post_interest_interest_id_fkey'),
    sa.ForeignKeyConstraint(['post_id'], ['general.id'], name='post_interest_post_id_fkey'),
    sa.PrimaryKeyConstraint('post_id', 'interest_id', name='post_interest_pkey')
    )
    # ### end Alembic commands ###
