"""New Migration

Revision ID: 2c1e6afcef75
Revises: 2f444e620e2b
Create Date: 2024-03-08 05:19:42.753270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1e6afcef75'
down_revision = '2f444e620e2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('general', 'longitude')
    op.drop_column('general', 'latitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general', sa.Column('latitude', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('general', sa.Column('longitude', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
