"""New Migration

Revision ID: 2c5fcac0bb1e
Revises: b83042854874
Create Date: 2024-02-06 03:49:06.241374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5fcac0bb1e'
down_revision = 'b83042854874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likedgeneralpost', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likedgeneralpost', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
