"""New Migration

Revision ID: 2e89f80d560d
Revises: 62616b478db9
Create Date: 2023-09-04 17:25:56.301192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e89f80d560d'
down_revision = '62616b478db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('country', sa.String(), nullable=True))
    op.add_column('event', sa.Column('state', sa.String(), nullable=True))
    op.add_column('event', sa.Column('city', sa.String(), nullable=True))
    op.drop_column('event', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('event', 'city')
    op.drop_column('event', 'state')
    op.drop_column('event', 'country')
    # ### end Alembic commands ###
