"""New Migration

Revision ID: 2f444e620e2b
Revises: 4ca89b725c4a
Create Date: 2024-03-07 02:12:52.455543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f444e620e2b'
down_revision = '4ca89b725c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interest_id'), 'interest', ['id'], unique=False)
    op.create_index(op.f('ix_interest_name'), 'interest', ['name'], unique=False)
    op.create_table('post_interest',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interest.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['general.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'interest_id')
    )
    op.add_column('general', sa.Column('interest_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'general', 'interest', ['interest_id'], ['id'])
    op.drop_column('general', 'interest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general', sa.Column('interest', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'general', type_='foreignkey')
    op.drop_column('general', 'interest_id')
    op.drop_table('post_interest')
    op.drop_index(op.f('ix_interest_name'), table_name='interest')
    op.drop_index(op.f('ix_interest_id'), table_name='interest')
    op.drop_table('interest')
    # ### end Alembic commands ###
