"""New Migration

Revision ID: 2fa23af1b282
Revises: 937764638627
Create Date: 2023-08-29 00:23:13.677228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa23af1b282'
down_revision = '937764638627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
