"""New Migration

Revision ID: 349d1c2a9bf9
Revises: 2fa23af1b282
Create Date: 2023-08-29 18:19:54.715116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349d1c2a9bf9'
down_revision = '2fa23af1b282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
