"""New Migration

Revision ID: 3814d0b5360d
Revises: b5ebe93d3b0b
Create Date: 2024-06-17 04:17:46.336832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3814d0b5360d'
down_revision = 'b5ebe93d3b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('business', sa.Column('user_ratings_count', sa.Integer(), nullable=True))
    op.drop_column('business', 'ratings')
    op.drop_column('business', 'user_ratings_total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('user_ratings_total', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('business', sa.Column('ratings', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('business', 'user_ratings_count')
    op.drop_column('business', 'rating')
    # ### end Alembic commands ###
