"""New Migration

Revision ID: 3845f77acb11
Revises: e1ae1c71493c
Create Date: 2024-02-06 03:32:42.770066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3845f77acb11'
down_revision = 'e1ae1c71493c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
