"""New Migration

Revision ID: 3a938656cfdb
Revises: 92755859bcc4
Create Date: 2024-06-07 07:34:50.255912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a938656cfdb'
down_revision = '92755859bcc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openinghours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('open_time', sa.String(), nullable=True),
    sa.Column('close_time', sa.String(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_openinghours_id'), 'openinghours', ['id'], unique=False)
    op.add_column('business', sa.Column('ratings', sa.Float(), nullable=True))
    op.add_column('business', sa.Column('user_ratings_total', sa.Integer(), nullable=True))
    op.add_column('business', sa.Column('photo_urls', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'photo_urls')
    op.drop_column('business', 'user_ratings_total')
    op.drop_column('business', 'ratings')
    op.drop_index(op.f('ix_openinghours_id'), table_name='openinghours')
    op.drop_table('openinghours')
    # ### end Alembic commands ###
