"""New Migration

Revision ID: 3d483f90a031
Revises: 2bde4b0b48a3
Create Date: 2024-02-20 02:23:22.509091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d483f90a031'
down_revision = '2bde4b0b48a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('free', sa.Column('bl_latitude', sa.String(), nullable=True))
    op.add_column('free', sa.Column('bl_longitude', sa.String(), nullable=True))
    op.add_column('free', sa.Column('tr_longitude', sa.String(), nullable=True))
    op.add_column('free', sa.Column('tr_latitude', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('free', 'tr_latitude')
    op.drop_column('free', 'tr_longitude')
    op.drop_column('free', 'bl_longitude')
    op.drop_column('free', 'bl_latitude')
    # ### end Alembic commands ###
