"""New Migration

Revision ID: 3ed697fa2121
Revises: 583eb057b363
Create Date: 2024-06-19 02:05:51.935078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed697fa2121'
down_revision = '583eb057b363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('user_rating_count', sa.Integer(), nullable=True))
    op.drop_column('business', 'user_ratings_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('user_ratings_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('business', 'user_rating_count')
    # ### end Alembic commands ###
