"""New Migration

Revision ID: 40b5a0ac5a26
Revises: 5715f82481d9
Create Date: 2024-06-15 07:07:26.878606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b5a0ac5a26'
down_revision = '5715f82481d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
