"""New Migration

Revision ID: 4509cecb4f8c
Revises: 5e4bc0cb70a9
Create Date: 2024-02-20 03:36:13.206782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4509cecb4f8c'
down_revision = '5e4bc0cb70a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
