"""New Migration

Revision ID: 4976f15c4d15
Revises: bc8164773c1d
Create Date: 2023-09-04 08:11:36.128719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4976f15c4d15'
down_revision = 'bc8164773c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sharedroomimage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shared_room_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shared_room_id'], ['sharedroom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sharedroomimage_id'), 'sharedroomimage', ['id'], unique=False)
    op.drop_column('sharedroom', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sharedroom', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sharedroomimage_id'), table_name='sharedroomimage')
    op.drop_table('sharedroomimage')
    # ### end Alembic commands ###
