"""New Migration

Revision ID: 4aff2199bee4
Revises: 3ed697fa2121
Create Date: 2024-06-19 02:45:05.057225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aff2199bee4'
down_revision = '3ed697fa2121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businessrequest', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businessrequest', 'description')
    # ### end Alembic commands ###
