"""New Migration

Revision ID: 4b8819f5a490
Revises: 83f1afc74022
Create Date: 2023-08-29 18:45:18.754266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8819f5a490'
down_revision = '83f1afc74022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
