"""New Migration

Revision ID: 4ca89b725c4a
Revises: ebfca97c2672
Create Date: 2024-03-03 06:50:46.251980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca89b725c4a'
down_revision = 'ebfca97c2672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('general', sa.Column('longitude', sa.String(), nullable=True))
    op.add_column('general', sa.Column('interest', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('general', 'interest')
    op.drop_column('general', 'longitude')
    op.drop_column('general', 'latitude')
    # ### end Alembic commands ###
