"""New Migration

Revision ID: 4dc1d516e1b4
Revises: e8def50dec26
Create Date: 2024-06-15 07:02:30.408689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc1d516e1b4'
down_revision = 'e8def50dec26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
