"""New Migration

Revision ID: 5125683141a9
Revises: e5b8e002b5e5
Create Date: 2024-06-19 01:11:10.899746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5125683141a9'
down_revision = 'e5b8e002b5e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
