"""New Migration

Revision ID: 544e18fb8bcb
Revises: a84ba08a9354
Create Date: 2024-02-20 03:07:06.475816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544e18fb8bcb'
down_revision = 'a84ba08a9354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
