"""New Migration

Revision ID: 5715f82481d9
Revises: 4dc1d516e1b4
Create Date: 2024-06-15 07:03:26.155717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5715f82481d9'
down_revision = '4dc1d516e1b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
