"""New Migration

Revision ID: 580f9c1fad8b
Revises: da4e39030956
Create Date: 2023-10-11 02:05:49.155008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580f9c1fad8b'
down_revision = 'da4e39030956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
