"""New Migration

Revision ID: 58626a3bb050
Revises: 3a938656cfdb
Create Date: 2024-06-11 06:53:28.713379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58626a3bb050'
down_revision = '3a938656cfdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
