"""New Migration

Revision ID: 59b836f8e7b8
Revises: 650102f58386
Create Date: 2023-08-29 19:27:00.261059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b836f8e7b8'
down_revision = '650102f58386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
