"""New Migration

Revision ID: 59cbcf4d3c64
Revises: 580f9c1fad8b
Create Date: 2023-10-13 00:59:38.771553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59cbcf4d3c64'
down_revision = '580f9c1fad8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
