"""New Migration

Revision ID: 59effd1ddefe
Revises: d48f51e13596
Create Date: 2023-08-29 22:38:04.314759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59effd1ddefe'
down_revision = 'd48f51e13596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businessimage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businessimage_id'), 'businessimage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_businessimage_id'), table_name='businessimage')
    op.drop_table('businessimage')
    # ### end Alembic commands ###
