"""New Migration

Revision ID: 5d2b5c0fb2f7
Revises: 59cbcf4d3c64
Create Date: 2023-11-10 02:44:39.820982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2b5c0fb2f7'
down_revision = '59cbcf4d3c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('address', sa.String(), nullable=True))
    op.add_column('event', sa.Column('address', sa.String(), nullable=True))
    op.add_column('free', sa.Column('address', sa.String(), nullable=True))
    op.add_column('house', sa.Column('address', sa.String(), nullable=True))
    op.add_column('job', sa.Column('address', sa.String(), nullable=True))
    op.add_column('sharedroom', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sharedroom', 'address')
    op.drop_column('job', 'address')
    op.drop_column('house', 'address')
    op.drop_column('free', 'address')
    op.drop_column('event', 'address')
    op.drop_column('business', 'address')
    # ### end Alembic commands ###
