"""New Migration

Revision ID: 5e4bc0cb70a9
Revises: 89254b7e447f
Create Date: 2024-02-20 03:30:27.245758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e4bc0cb70a9'
down_revision = '89254b7e447f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
