"""New Migration

Revision ID: 62616b478db9
Revises: 6b582970455b
Create Date: 2023-09-04 16:31:24.135395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62616b478db9'
down_revision = '6b582970455b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
