"""New Migration

Revision ID: 6494592dae22
Revises: 74ddad8d8eeb
Create Date: 2024-02-15 00:26:38.344383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6494592dae22'
down_revision = '74ddad8d8eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
