"""New Migration

Revision ID: 650102f58386
Revises: cf6eca28240b
Create Date: 2023-08-29 19:18:46.645672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650102f58386'
down_revision = 'cf6eca28240b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
