"""New Migration

Revision ID: 6b582970455b
Revises: a2a2d1e4d14a
Create Date: 2023-09-04 16:15:43.328988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b582970455b'
down_revision = 'a2a2d1e4d14a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
