"""New Migration

Revision ID: 6b74c60fb403
Revises: 147f0aa257d6
Create Date: 2023-08-28 23:51:33.504099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b74c60fb403'
down_revision = '147f0aa257d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
