"""New Migration

Revision ID: 6e72a97d6616
Revises: c058b81a9b1d
Create Date: 2024-02-10 21:50:43.585539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e72a97d6616'
down_revision = 'c058b81a9b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
