"""New Migration

Revision ID: 74ddad8d8eeb
Revises: dabc44ce6d9c
Create Date: 2024-02-14 18:10:41.724083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ddad8d8eeb'
down_revision = 'dabc44ce6d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('upvote', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('downvote', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'downvote')
    op.drop_column('comment', 'upvote')
    # ### end Alembic commands ###
