"""New Migration

Revision ID: 76e7af7a189a
Revises: d59fef90e328
Create Date: 2023-09-16 05:04:07.579189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e7af7a189a'
down_revision = 'd59fef90e328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
