"""New Migration

Revision ID: 7a418b5592eb
Revises: cdb34c964750
Create Date: 2024-06-14 08:15:55.296560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a418b5592eb'
down_revision = 'cdb34c964750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('ratings', sa.Float(), nullable=True))
    op.add_column('business', sa.Column('user_ratings_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'user_ratings_total')
    op.drop_column('business', 'ratings')
    # ### end Alembic commands ###
