"""New Migration

Revision ID: 7fc4974eefb4
Revises: f4cd85aea310
Create Date: 2023-03-21 01:50:12.833299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc4974eefb4'
down_revision = 'f4cd85aea310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
