"""New Migration

Revision ID: 8167dce79fc5
Revises: 349d1c2a9bf9
Create Date: 2023-08-29 18:26:15.926078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8167dce79fc5'
down_revision = '349d1c2a9bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
