"""New Migration

Revision ID: 83f1afc74022
Revises: 8167dce79fc5
Create Date: 2023-08-29 18:43:34.413809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f1afc74022'
down_revision = '8167dce79fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
