"""New Migration

Revision ID: 889347eaf5cc
Revises: 8ab137fdff5a
Create Date: 2024-06-01 07:28:49.973353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889347eaf5cc'
down_revision = '8ab137fdff5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
