"""New Migration

Revision ID: 89254b7e447f
Revises: a3a62f916eb2
Create Date: 2024-02-20 03:18:03.206891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89254b7e447f'
down_revision = 'a3a62f916eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
