"""New Migration

Revision ID: 8ab137fdff5a
Revises: 2beb7407deeb
Create Date: 2024-05-16 07:35:33.490065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab137fdff5a'
down_revision = '2beb7407deeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('business', sa.Column('longitude', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'longitude')
    op.drop_column('business', 'latitude')
    # ### end Alembic commands ###
