"""New Migration

Revision ID: 8ad46b9e4ca5
Revises: 9aa2b15bc8e3
Create Date: 2023-09-19 06:07:47.458428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ad46b9e4ca5'
down_revision = '9aa2b15bc8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
