"""New Migration

Revision ID: 8f75593e2b6e
Revises: f3b94a82d72e
Create Date: 2023-08-21 00:29:00.332241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f75593e2b6e'
down_revision = 'f3b94a82d72e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('country', sa.String(), nullable=True))
    op.add_column('business', sa.Column('state', sa.String(), nullable=True))
    op.add_column('business', sa.Column('city', sa.String(), nullable=True))
    op.drop_column('business', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('business', 'city')
    op.drop_column('business', 'state')
    op.drop_column('business', 'country')
    # ### end Alembic commands ###
