"""New Migration

Revision ID: 90c3f8f3bcf9
Revises: 76e7af7a189a
Create Date: 2023-09-16 05:53:51.171273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c3f8f3bcf9'
down_revision = '76e7af7a189a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
