"""New Migration

Revision ID: 91895ee943bd
Revises: 4509cecb4f8c
Create Date: 2024-02-21 04:36:12.425816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91895ee943bd'
down_revision = '4509cecb4f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('free', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('free', sa.Column('longitude', sa.String(), nullable=True))
    op.drop_column('free', 'bl_latitude')
    op.drop_column('free', 'tr_longitude')
    op.drop_column('free', 'tr_latitude')
    op.drop_column('free', 'bl_longitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('free', sa.Column('bl_longitude', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('free', sa.Column('tr_latitude', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('free', sa.Column('tr_longitude', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('free', sa.Column('bl_latitude', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('free', 'longitude')
    op.drop_column('free', 'latitude')
    # ### end Alembic commands ###
