"""New Migration

Revision ID: 92755859bcc4
Revises: 889347eaf5cc
Create Date: 2024-06-07 07:28:32.425729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92755859bcc4'
down_revision = '889347eaf5cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
