"""New Migration

Revision ID: 937764638627
Revises: 2b5cf13f8bb0
Create Date: 2023-08-29 00:17:30.974463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937764638627'
down_revision = '2b5cf13f8bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
