"""New Migration

Revision ID: 9967980b817c
Revises: a7a9469f6ac2
Create Date: 2023-09-16 04:16:12.749593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9967980b817c'
down_revision = 'a7a9469f6ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
