"""New Migration

Revision ID: 9aa2b15bc8e3
Revises: 820ff26bd8bd
Create Date: 2023-09-19 06:01:25.361326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa2b15bc8e3'
down_revision = '820ff26bd8bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
