"""New Migration

Revision ID: 9ab368676d8b
Revises: 1242ddc162b5
Create Date: 2024-06-11 07:01:40.007835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab368676d8b'
down_revision = '1242ddc162b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_openinghours_id', table_name='openinghours')
    op.drop_table('openinghours')
    op.drop_column('business', 'photo_urls')
    op.drop_column('business', 'ratings')
    op.drop_column('business', 'user_ratings_total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('user_ratings_total', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('business', sa.Column('ratings', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('business', sa.Column('photo_urls', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('openinghours',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('open_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('close_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], name='openinghours_business_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='openinghours_pkey')
    )
    op.create_index('ix_openinghours_id', 'openinghours', ['id'], unique=False)
    # ### end Alembic commands ###
