"""New Migration

Revision ID: a2a2d1e4d14a
Revises: 4976f15c4d15
Create Date: 2023-09-04 08:18:38.316956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a2d1e4d14a'
down_revision = '4976f15c4d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
