"""New Migration

Revision ID: a3a62f916eb2
Revises: 544e18fb8bcb
Create Date: 2024-02-20 03:09:42.923032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a62f916eb2'
down_revision = '544e18fb8bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
