"""New Migration

Revision ID: a3c91ec4d816
Revises: 9967980b817c
Create Date: 2023-09-16 04:41:04.301656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c91ec4d816'
down_revision = '9967980b817c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
