"""New Migration

Revision ID: a4170c35c4ac
Revises: 6a400c972ba1
Create Date: 2023-09-04 06:07:37.964566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4170c35c4ac'
down_revision = '6a400c972ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
