"""New Migration

Revision ID: a55cf6aeda56
Revises: e03d4c7e6280
Create Date: 2024-02-03 04:21:44.902314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a55cf6aeda56'
down_revision = 'e03d4c7e6280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'owner_id')
    # ### end Alembic commands ###
