"""New Migration

Revision ID: a84ba08a9354
Revises: 2a43291639bc
Create Date: 2024-02-20 02:53:12.914309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a84ba08a9354'
down_revision = '2a43291639bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
