"""New Migration

Revision ID: a96347de7b98
Revises: d2576d188323
Create Date: 2024-02-06 03:41:08.173858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96347de7b98'
down_revision = 'd2576d188323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
