"""postid for sharedroom

Revision ID: afe07009d755
Revises: c94c7eb4c042
Create Date: 2023-09-16 19:49:43.236110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe07009d755'
down_revision = 'c94c7eb4c042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
