"""New Migration

Revision ID: b5ebe93d3b0b
Revises: 1ab4dc84f4b7
Create Date: 2024-06-15 07:12:03.966040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ebe93d3b0b'
down_revision = '1ab4dc84f4b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businessrequest', 'approved')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businessrequest', sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
