"""New Migration

Revision ID: be8253b233c5
Revises: 2dda987130d4
Create Date: 2023-09-04 04:46:51.910076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be8253b233c5'
down_revision = '2dda987130d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'image_urls')
    op.drop_column('event', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('image_urls', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
