"""New Migration

Revision ID: c058b81a9b1d
Revises: 107ac3656539
Create Date: 2024-02-06 06:45:42.202073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c058b81a9b1d'
down_revision = '107ac3656539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('updowngeneralpost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('general_post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('upvote', sa.Boolean(), nullable=True),
    sa.Column('downvote', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_updowngeneralpost_id'), 'updowngeneralpost', ['id'], unique=False)
    op.drop_index('ix_likedgeneralpost_id', table_name='likedgeneralpost')
    op.drop_table('likedgeneralpost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likedgeneralpost',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('general_post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='likedgeneralpost_pkey')
    )
    op.create_index('ix_likedgeneralpost_id', 'likedgeneralpost', ['id'], unique=False)
    op.drop_index(op.f('ix_updowngeneralpost_id'), table_name='updowngeneralpost')
    op.drop_table('updowngeneralpost')
    # ### end Alembic commands ###
