"""New Migration

Revision ID: c197fd0d54e0
Revises: 04633c4d5560
Create Date: 2024-06-15 06:59:30.953039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c197fd0d54e0'
down_revision = '04633c4d5560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
