"""New Migration

Revision ID: c51e2b60eba4
Revises: 59b836f8e7b8
Create Date: 2023-08-29 19:32:56.767092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51e2b60eba4'
down_revision = '59b836f8e7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
