"""New Migration

Revision ID: c94c6a014744
Revises: 3845f77acb11
Create Date: 2024-02-06 03:35:11.775168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94c6a014744'
down_revision = '3845f77acb11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
