"""New Migration

Revision ID: cdb34c964750
Revises: 9ab368676d8b
Create Date: 2024-06-14 08:09:50.878046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb34c964750'
down_revision = '9ab368676d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
