"""New Migration

Revision ID: cf6eca28240b
Revises: 11b14f42f75f
Create Date: 2023-08-29 19:04:04.248659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6eca28240b'
down_revision = '11b14f42f75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
