"""New Migration

Revision ID: d2576d188323
Revises: c94c6a014744
Create Date: 2024-02-06 03:37:23.250479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2576d188323'
down_revision = 'c94c6a014744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likedgeneralpost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('general_post_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_likedgeneralpost_id'), 'likedgeneralpost', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_likedgeneralpost_id'), table_name='likedgeneralpost')
    op.drop_table('likedgeneralpost')
    # ### end Alembic commands ###
