"""New Migration

Revision ID: d59fef90e328
Revises: a3c91ec4d816
Create Date: 2023-09-16 04:53:06.013583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59fef90e328'
down_revision = 'a3c91ec4d816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
