"""New Migration

Revision ID: d6d9ce287fee
Revises: c91d6ce25757
Create Date: 2023-09-04 05:46:36.061010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d9ce287fee'
down_revision = 'c91d6ce25757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
