"""New Migration

Revision ID: da4e39030956
Revises: 10e7e635e8bd
Create Date: 2023-10-06 00:19:38.506306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4e39030956'
down_revision = '10e7e635e8bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house', sa.Column('house_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('house', 'house_type')
    # ### end Alembic commands ###
