"""New Migration

Revision ID: dabc44ce6d9c
Revises: 6e72a97d6616
Create Date: 2024-02-14 01:55:01.573250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dabc44ce6d9c'
down_revision = '6e72a97d6616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general', sa.Column('address', sa.String(), nullable=True))
    op.add_column('general', sa.Column('country', sa.String(), nullable=True))
    op.add_column('general', sa.Column('state', sa.String(), nullable=True))
    op.add_column('general', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('general', 'city')
    op.drop_column('general', 'state')
    op.drop_column('general', 'country')
    op.drop_column('general', 'address')
    # ### end Alembic commands ###
