"""New Migration

Revision ID: e1ae1c71493c
Revises: e3292da4d6d6
Create Date: 2024-02-05 02:49:53.874912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ae1c71493c'
down_revision = 'e3292da4d6d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
