"""New Migration

Revision ID: e4abca40c944
Revises: 8ad46b9e4ca5
Create Date: 2023-09-19 06:42:17.357828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4abca40c944'
down_revision = '8ad46b9e4ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userpayment',
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_userpayment_payment_id'), 'userpayment', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userpayment_payment_id'), table_name='userpayment')
    op.drop_table('userpayment')
    # ### end Alembic commands ###
