"""New Migration

Revision ID: e8def50dec26
Revises: c197fd0d54e0
Create Date: 2024-06-15 07:00:50.496742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8def50dec26'
down_revision = 'c197fd0d54e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
