"""New Migration

Revision ID: f3b94a82d72e
Revises: 7fc4974eefb4
Create Date: 2023-03-21 01:52:47.502748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b94a82d72e'
down_revision = '7fc4974eefb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
