"""New Migration

Revision ID: f4cd85aea310
Revises: a2a917e2654f
Create Date: 2023-03-21 01:43:35.396044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4cd85aea310'
down_revision = 'a2a917e2654f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
